backend:
  name: github
  repo: torresgomezedgar/blog-decap
  branch: main
  auth_type: oauth
  base_url: https://blog-auth-c82h.onrender.com
  auth_endpoint: /auth
  app_id: Ov23lieB8tMXJlRAsDPA
  #site_url: https://blog-decap.vercel.app
  #display_url: https://blog-decap.vercel.app
  #locale: "es"

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }
